CREATE DATABASE InLock_Games;
GO

USE InLock_Games;
GO

CREATE TABLE Estudios (
	IdEstudio INT PRIMARY KEY IDENTITY,
	NomeEstudio VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE Jogos (
	IdJogo INT PRIMARY KEY IDENTITY,
	NomeJogo VARCHAR (255) NOT NULL,
	DescricaoJogo VARCHAR (255) NOT NULL,
	DataLancamento DATE NOT NULL,
	ValorJogo MONEY NOT NULL,
	IdEstudio INT FOREIGN KEY REFERENCES Estudios (IdEstudio) NOT NULL 
);

CREATE TABLE TiposUsuarios (
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	NomeTipoUsuario VARCHAR (255) NOT NULL
);

CREATE TABLE Usuarios (
	IdUsuario INT PRIMARY KEY IDENTITY,
	NomeUsuario VARCHAR (100) NOT NULL,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Senha VARCHAR (255) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES  TiposUsuarios (IdTipoUsuario) NOT NULL
);
GO



